ExUnit.start(exclude: [:compatibility, :integration])
Code.require_file("test/support/state_store_harness.ex")
Code.require_file("test/support/fake_smsc.ex")
Code.require_file("test/support/rabbit_mq_measurements.ex")
Code.require_file("test/support/rabbit_mq_harness.ex")
